mysql:
  host: '192.168.32.192'
  port: 3306
  name: 'inventory'
  db: 'inventory'
  user: 'root'
  password: '0987654321!Aa'

nacos:
  host: '192.168.32.192'
  port: 8848
  namespace: 'ca51d985-40bf-482c-948b-cae51a6f7843'
  dataid: 'inventory.json'
  group: 'dev'
  user: 'nacos'
  password: 'nacos'

