mysql:
  host: '192.168.32.192'
  port: 3306
  name: 'goods_srv'
  db: 'goods_srv'
  user: 'root'
  password: '0987654321!Aa'

nacos:
  host: '192.168.32.192'
  port: 8848
  namespace: 'fc8103da-ea3d-406f-91eb-11249e39298f'
  dataid: 'goods_srv.json'
  group: 'dev'
  user: 'nacos'
  password: 'nacos'

